### ISSUE TITLE
Correct path to put datase file

### ISSUE THREAD

**Issue by alfianakbar** [gyrdym/ml_dataframe#16]
I have got this error message:
`[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: FileSystemException: Cannot open file, path = 'assets/diabetes.csv' (OS Error: No such file or directory, errno = 2)`

Here is assets path my pubspec.yaml:
```
assets:
  - assets/diabetes.csv
```

my assets directory:
<img width="208" alt="Screen Shot 2020-06-06 at 0 13 21" src="https://user-images.githubusercontent.com/989885/83904722-91b36500-a78a-11ea-947a-a35fbaaa1072.png">

My call:
`final samples = await fromCsv('assets/diabetes.csv', headerExists: true);`

Please help me, thanks!

**Comment by Ardib0ys** [comment]
> @febryituery ok, I see, the issue still exists, I'll transfer it to a different lib (ml_dataframe), since it isn't connected to ml_algo

@gyrdym is this issue been resolved?

**Comment by gyrdym** [comment]
> > @febryituery ok, I see, the issue still exists, I'll transfer it to a different lib (ml_dataframe), since it isn't connected to ml_algo
> 
> 
> 
> @gyrdym is this issue been resolved?

Not yet, I'm working on it.

**Comment by gyrdym** [comment]
@febryituery @febryituery @Ardib0ys have you tried `path_provider` package to form a proper file path to access the dataset? There is a great [article](https://flutter.dev/docs/cookbook/persistence/reading-writing-files) explaining the main aspects of working with files. Your issue seems to be flutter-related, and since packages `ml_algo` and `ml_dataframe` are framework-agnostic, I can't add flutter-specific logic to these packages, you need to resolve file paths on your side. @febryituery `loadAsset()` works because it uses functionality from flutter SDK, `loadString()` method resolves the path internally.

**Comment by gyrdym** [comment]
@febryituery try to add `path_provider` package to your pubspec.yaml:

```
dependencies:
  path_provider: ^1.6.24
```

After that try the following code:

```dart
final directory = await getApplicationDocumentsDirectory(); // getApplicationDocumentsDirectory is a function from `path_provider` package
final filePath = `${directory.path}/assets/datapasienfix.csv`;
final samples = await fromCsv(filePath);
```

**Comment by febryituery** [comment]
> @febryituery try to add `path_provider` package to your pubspec.yaml:
> 
> ```
> dependencies:
>   path_provider: ^1.6.24
> ```
> 
> After that try the following code:
> 
> ```dart
> final directory = await getApplicationDocumentsDirectory(); // getApplicationDocumentsDirectory is a function from `path_provider` package
> final filePath = `${directory.path}/assets/datapasienfix.csv`;
> final samples = await fromCsv(filePath);
> ```

Hi, thanks for your reply.
i try this but still get an error

`E/flutter ( 4951): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot open file, path = '/data/data/com.android.ml_kit/app_flutter/assets/datasets/datapasienfix.csv' (OS Error: No such file or directory, errno = 2)
E/flutter ( 4951): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter ( 4951): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 4951): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 4951): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 4951): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 4951): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 4951): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 4951): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 4951): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 4951): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 4951): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 4951): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 4951): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 4951): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
`

<img width="592" alt="Jepretan Layar 2020-12-27 pukul 03 37 09" src="https://user-images.githubusercontent.com/16750465/103158828-fc92bf00-47f4-11eb-88c1-e57176d1f992.png">

<img width="200" alt="Jepretan Layar 2020-12-27 pukul 03 37 20" src="https://user-images.githubusercontent.com/16750465/103158833-01f00980-47f5-11eb-9188-c20fee79ec66.png">

Am i missing something?

**Comment by gyrdym** [comment]
@febryituery could you please try `getLibraryDirectory` or `getApplicationSupportDirectory` instead of `getApplicationDocumentsDirectory` from the same package?

**Comment by febryituery** [comment]
> @febryituery could you please try `getLibraryDirectory` or `getApplicationSupportDirectory` instead of `getApplicationDocumentsDirectory` from the same package?

still get an error. i use `getApplicationSupportDirectory()` because i only use android for this project.

`E/flutter (17592): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot open file, path = '/data/data/com.example.recheck/files/assets/datapasienfix.csv' (OS Error: No such file or directory, errno = 2)
E/flutter (17592): #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
E/flutter (17592): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (17592): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (17592): #3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (17592): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (17592): #5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (17592): #6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (17592): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (17592): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (17592): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (17592): #10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (17592): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (17592): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (17592): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)`

<img width="510" alt="Jepretan Layar 2020-12-28 pukul 14 45 43" src="https://user-images.githubusercontent.com/16750465/103198675-7755fa00-491b-11eb-9a08-0c2584644768.png">

<img width="262" alt="Jepretan Layar 2020-12-28 pukul 14 45 55" src="https://user-images.githubusercontent.com/16750465/103198679-7ae98100-491b-11eb-9976-e10117979f57.png">

<img width="239" alt="Jepretan Layar 2020-12-28 pukul 14 46 02" src="https://user-images.githubusercontent.com/16750465/103198685-7de47180-491b-11eb-92d8-34fabda21859.png">

**Comment by gyrdym** [comment]
@febryituery Oh, ok, I see. I'm not a flutter developer, I didn't know some things, for instance, that Flutter moves assets directory into a special location during runtime. Apparently, `getApplicationDocumentsDirectory` points to this special directory. Could you please alter a bit a code snippet I suggested you earlier:

```Dart
import 'package:path/path.dart';;

final directory = await getApplicationDocumentsDirectory();
final filePath = join(directory.path, 'datapasienfix.csv'); // Notice here, I removed `assets` directory mention, apparently we don't need it in runtime
final samples = await fromCsv(filePath);
```

**Comment by gyrdym** [comment]
@febryituery And the ugliest thing as our last resort - copy the asset's content and write it to our app directory and then read it:

```Dart
import 'dart:async';
import 'dart:io';
import 'package:flutter/services.dart' show rootBundle;
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart';

final fileName = 'dataset.csv';
final bytes = await rootBundle.load('assets/datasets/datapasienfix.csv');
final dir = (await getApplicationDocumentsDirectory()).path;
final filePath = join(dir, fileName);

await writeToFile(bytes, filePath);

final samples = await fromCsv(filePath);

//write to app path
Future<void> writeToFile(ByteData data, String path) {
  final buffer = data.buffer;
  
  return new File(path).writeAsBytes(
      buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
}
```

**Comment by febryituery** [comment]
> @febryituery And the ugliest thing as our last resort - copy the asset's content and write it to our app directory and then read it:
> 
> ```dart
> import 'dart:async';
> import 'dart:io';
> import 'package:flutter/services.dart' show rootBundle;
> import 'package:path_provider/path_provider.dart';
> 
> final filename = 'dataset.csv';
> final bytes = await rootBundle.load('assets/datasets/datapasienfix.csv');
> final dir = (await getApplicationDocumentsDirectory()).path;
> final filePath = '$dir/$filename';
> 
> await writeToFile(bytes, filePath);
> 
> final samples = await fromCsv(filePath);
> 
> //write to app path
> Future<void> writeToFile(ByteData data, String path) {
>   final buffer = data.buffer;
>   
>   return new File(path).writeAsBytes(
>       buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
> }
> ```

okay, i'll try this solution and comeback if error still exist

**Comment by febryituery** [comment]
> @febryituery And the ugliest thing as our last resort - copy the asset's content and write it to our app directory and then read it:
> 
> ```dart
> import 'dart:async';
> import 'dart:io';
> import 'package:flutter/services.dart' show rootBundle;
> import 'package:path_provider/path_provider.dart';
> import 'package:path/path.dart';
> 
> final fileName = 'dataset.csv';
> final bytes = await rootBundle.load('assets/datasets/datapasienfix.csv');
> final dir = (await getApplicationDocumentsDirectory()).path;
> final filePath = join(dir, fileName);
> 
> await writeToFile(bytes, filePath);
> 
> final samples = await fromCsv(filePath);
> 
> //write to app path
> Future<void> writeToFile(ByteData data, String path) {
>   final buffer = data.buffer;
>   
>   return new File(path).writeAsBytes(
>       buffer.asUint8List(data.offsetInBytes, data.lengthInBytes));
> }
> ```

This solution work for me. I think i will use this solution as temporary solution, and figure it out in another time since this project only for research purpose not production purpose.
Thank you for your support, i will close this issue.

**Comment by gyrdym** [comment]
@febryituery great, from my side - I'll add a new factory for DataFrame in `ml_dataframe` in order to make it possible to create a dataframe from raw csv content which one can get by calling rootBundle.loadString(...)

**Comment by febryituery** [comment]
> @febryituery great, from my side - I'll add a new factory for DataFrame in `ml_dataframe` in order to make it possible to create a dataframe from raw csv content which one can get by calling rootBundle.loadString(...)

Excellent 👍🏻
